# Generated by Django 4.1.7 on 2023-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(db_column='St_Rollno', max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('physics', models.FloatField(max_length=3)),
                ('chemistry', models.FloatField(max_length=3)),
                ('maths', models.FloatField(max_length=3)),
            ],
        ),
    ]
